name: gh-pages

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install dependencies
        run: pnpm i

      - name: Build Carta
        run: pnpm run build
        working-directory: packages/carta-md

      - name: Build Plugin Math
        run: pnpm run build
        working-directory: packages/plugin-math

      # - name: Build packages
      #   run: pnpm run build

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/build
